spring.application.name=url-shortener

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=url_shortener
spring.datasource.password=url_shortener

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true